title: "Verification of CoreSwap: Replacing ARM Cortex-A5 with RISC-V CVA6 in ARM SoC Environment"
authors: "Muhammad Hammad Bashir, Umer Shahid, Muhammad Tahir, Yazan Hussnain, and Fatima Saleem"
venue: "RISC-V Summit Europe 2025"
year: "2025"
link: "https://riscv-europe.org/summit/2025/posters"
sortOrder: 4
